### PR TITLE
Alert Features

### PR DESCRIPTION
**Pull request by kimzeuner**
As discussed in PR #182 new features and the camera component should be divided as there is still some experience with the camera missing. With this PR only the read and delete alert features are added as i think they can be really helpful.
Everything is working for me so let me know if you have any problems.

### CODE REVIEW

**Comment by jm-73** [comment]
I think we need to document how to use this functions...

**Comment by jm-73** [comment]
I have commited your updated texts in the README to the devlop-branch. So in the next release this will be committed to master branch.

**Comment by jm-73** [comment]
Thanks for your contribution!

**Comment by sander1988** [comment]
I did optimize this PR a bit ; changes are on the develop branch (commit 9db8f53959c06f59c11fb10cfd127c36dab64f0a):
- All alert related entities are now attributes on the main alert entity.
- Tracking of the full alert history is now disabled by default and can be enabled by the user using the config. This is for performance reasons, see the HA developer notes for more info: https://developers.home-assistant.io/docs/core/entity/
- Fix a bug where old alerts where not removed from HA.
- The alerts can now be translated. I have added the EN and NL translations.

**Pull request merged**
