### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jm-73**
Updated documentation to reflect changes in API/code
Updated icons in HA
Removed serial in config (not needed)
Changed one screenshot

### CODE REVIEW

**Review by pinsdorf — COMMENTED** [review]
I would not completly drop any mentions of `id` parameter. Existing users will have the question if they should remove the parameter from their config or keep it. Furthermore, what happens if I would own two mow robots (my neighbor does)? How are they distinguuished?

**Review by pinsdorf — COMMENTED** [review]
As of now the attribute `next_mow` has `device_class: timestamp`. If you set it to `None` there might be parsing issues in existing automations. Is there a legitimate way to express "None" as ISO date? Maybe `0000-00-00T00:00:00` - not perfect, but I'd prefer this over a text string. 

In any case, please add the special value also add to docs. Thanks.

**Comment by Shamshala** [comment]
> As of now the attribute `next_mow` has `device_class: timestamp`. If you set it to `None` there might be parsing issues in existing automations. Is there a legitimate way to express "None" as ISO date? Maybe `0000-00-00T00:00:00` - not perfect, but I'd prefer this over a text string.
> 
> In any case, please add the special value also add to docs. Thanks.

I don't see a problem of keeping the old timestamp until next_mow is set but I think the proper way used by many official sensors is setting "unavailable" state. For instance, "sensor.xxxxxx_next_alarm" of companion app uses this.

**Comment by Shamshala** [comment]
@pinsdorf @jm-73 I don't see a problem of keeping the old timestamp until next_mow is set but I think the proper way used by many official sensors is setting "unavailable" state. For instance, "sensor.xxxxxx_next_alarm" of companion app uses this.

**Comment by Shamshala** [comment]
@pinsdorf @jm-73 I don't see a problem of keeping the old timestamp until `next_mow` is set but I think the proper way used by many official sensors is setting `unavailable` state. For instance `sensor.xxxxxx_next_alarm` of companion app uses this.

`None` isn't gonna upset only automations, even rest of parts of HA won't like it.

**Comment by eavanvalkenburg** [comment]
I agree, unavailable or unknown is the way to go!

**Pull request closed without merging**
