### PR TITLE
Alerts with mower serial

### PR DESCRIPTION
**Pull request by kimzeuner**
Added the mower serial to the alert features to be able to select the mower when multiple mowers are configured.
Mower serial is optional and must not be used when only one mower is configured.
Also added de.json translation file.

Used developer branch with version 5.6.2 as base.

### CODE REVIEW

**Comment by sander1988** [comment]
@kimzeuner - I expect to test and merge this within a couple of days. Can you update the DE translation file? It got outdated due to some new functionality I just merged.

**Comment by kimzeuner** [comment]
Sure, should be fixed. Let me know if anything is missing.

**Comment by kimzeuner** [comment]
en.json update finished

**Comment by kimzeuner** [comment]
Because we are talking about translations, do you know how i can translate the entity names and states with the translation files ? I tried to translate the state from the Alert entities from No Problem into german but with the path from the HA developer docs it didn't work. It was something like 
```
"entities": {
  "sensors": {
    "entity_id": {
      "state": {
        "No Problem": "Kein Problem"
      }
    }
  }
}
    
```
Also in the developer docs i have read that the state, name or whatever must be defined with a translation_key but i don't know how to use this.

**Comment by sander1988** [comment]
> I tried to translate the state from the Alert entities from No Problem into german but with the path from the HA developer docs it didn't work.

See commit 75d24684be26aa31d5ee66316f18f7984f1ec1f6 ; this works. I have added 'No problem'. Please create a new PR in case you would like to add more. But for me this not really a priority.

**Comment by kimzeuner** [comment]
Ok, i will try that. Thanks. I understand this is not on your priority list at the moment, i'm just looking for things where i can support/make the integration a bit better without deep programmer knowledge 😉.

**Comment by sander1988** [comment]
@kimzeuner - Can you check Discord when you have time? I have sent you some questions. Hope you can help.

**Pull request merged**
